theme: jekyll-theme-leap-day
title: 2nd International Joint Conference on Learning & Reasoning (IJCLR)
description: Cumberland Lodge, Windsor Great Park, United Kingdom, 28-30 September 2022
show_downloads: false
