theme: jekyll-theme-leap-day
show_downloads: false
title: International Joint Conference on Learning & Reasoning (IJCLR)
subtitle: Cumberland Lodge, Windsor Great Park, United Kingdom, 28-30 September 2022
